baseurl = "https://jiangjun.netlify.com/"
languageCode = "zh-CN"
title = "Jackie"
theme = "hugo-ivy"
googleAnalytics = ""
disqusShortname = "jiangjun-netlify"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:slug/"
    note = "/note/:year/:month/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "Jackie's Personal Blog."
    footer = "&copy; Jackie  @2018 | [Github](https://github.com/JackieMium) | [Twitter](https://mobile.twitter.com/JackieMiem)"

  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdn.bootcss.com"
  highlightjsLang = ["r", "yaml", "tex", "python", "postgres", "postgresql", "sql", "bash", "shell"]
  highlightjsTheme = "github"
